SampleIM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

from SampleIM import settings

urlpatterns = [
    path('im/', include('im.urls')),
    path('imapi/', include('imapi.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(),{'next_page': settings.LOGIN_REDIRECT_URL}, name='login'),# name='login',定向login.html
    # path('accounts/logout/', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 静态文件开发时调试使用

im/urls.py
from django.urls import path

from im import views

app_name = 'im' # 你的应用名

urlpatterns = [
	path('', views.talkRoom, name='talkRoom'),
    path('signup/', views.signup, name="signup"),
    path('getLogout/', views.getLogout, name="getLogout"),
    path('getLogin/', views.getLogin, name="getLogin"),
]

im/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User # 导入 Django 验证系统
from django.conf import settings

MTC = [
    ('T', 'TXT'),
    ('P', 'IMAGINE'),
    ('V', 'VIDEO'),
    ('I', 'EMOJI'),
]

# Create your models here.
class UserProfile(models.Model):
    """用户扩展信息"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    introduce = models.CharField(max_length=120)
    online = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class UserRelation(models.Model):
    """用户-用户信息"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user') # 请求好友的一方
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user2')
    umid = models.PositiveIntegerField(default=0) # 记录用户 1 接收的用户 1、2 之间的信息 id 
    umid2 = models.PositiveIntegerField(default=0) # 同上
    create_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '%s -> %s'%(self.user.username, self.user2.username)

class Group(models.Model):
    """群组信息"""
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    create_time = models.DateTimeField(default=timezone.now)
    introduce = models.CharField(max_length=120)
    
    def __str__(self):
        return self.name

class GroupUser(models.Model):
    """群组-用户信息"""
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    join_time = models.DateTimeField(default=timezone.now)
    gmid = models.PositiveIntegerField(default=0) # 记录用户接收的消息

    def __str__(self):
        return '%s->>%s'%(self.user.username, self.group.name)

class UserMessage(models.Model):
    """用户之间消息"""
    userrelation = models.ForeignKey(UserRelation, on_delete=models.CASCADE)
    message = models.CharField(max_length=240)
    time = models.DateTimeField(default=timezone.now)
    receiver = models.CharField(max_length=60)
    sender = models.CharField(max_length=60) # 发送人 == UserRelation 中 userName
    MESSAGE_TYPE_CHOICES = MTC
    mtype = models.CharField(
        max_length=2,
        choices=MESSAGE_TYPE_CHOICES,
        default='T',
    )

    def __str__(self):
        return 'type %s -%s: %s->%s '%(self.mtype, str(self.time), self.sender, self.receiver) + str(self.pk)

class GroupMessage(models.Model):
    """群消息"""
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    message = models.CharField(max_length=120)
    time = models.DateTimeField(default=timezone.now)
    sender = models.CharField(max_length=60)
    MESSAGE_TYPE_CHOICES = MTC
    mtype = models.CharField(
        max_length=2,
        choices=MESSAGE_TYPE_CHOICES,
        default='T',
    )

    def __str__(self):
        return 'type %s -%s:%s: %s'%(self.mtype, str(self.time), self.group, self.sender)

class SaveImage(models.Model):
    """存储接收的图片信息"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image_file = models.ImageField(upload_to='images/%Y')
    time = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return '%s-%s'%(self.user.username, self.image_file)

im/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib.auth.models import User # 导入 Django 验证系统
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, login, authenticate
from django.core.exceptions import ObjectDoesNotExist


from .models import UserProfile, UserRelation, Group, GroupUser, UserMessage, GroupMessage


# Create your views here.

# def sendmessage(request):
#     """发送消息"""
#     user = request.user
#     sender = request.user.username
#     message = request.POST['groupmessage']
#     # print(sender,request.POST,message=='')
#     group,created = Group.objects.get_or_create(name = 'firsttest') # 测试用群
#     gp = GroupMessage.objects.create(group=group, message=message, sender=sender) # 保存群消息
#     group,created = GroupUser.objects.get_or_create(group=group,user=user,groupName='firsttest',userName=sender) # 建立群用户关系
#     return redirect('im:talkRoom')


@login_required
def talkRoom(request):
    """返回群消息，用户消息"""
    try:
        Group.objects.get(name='firsttest') # 测试用群
    except ObjectDoesNotExist:
        Group.objects.get_or_create(name='firsttest',creator=request.user) # 测试用群
    return render(request, 'im/chatroom2.html', {'gourpmessages': ''}) #


def getLogin(request):
    """保存用户登录时间"""
    return redirect('im:talkRoom')

def getLogout(request):
    """重定向至登录页面"""
    logout(request) # 登出
    return redirect('im:talkRoom')

#----------signup------------------------------------------------------------
def signup(request):#用户注册
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password) # 用户注册，返回用户对象
            login(request, user) # 执行登录过程
            return redirect('im:talkRoom')
    else:
        form = UserCreationForm()
    return render(request, 'im/signup.html', {'form':form})

# from im.models import SaveImage
# def testform(request):
#     """测试表单"""
#     print('length', request.META['CONTENT_LENGTH'])
#     bf = request.FILES
#     print(bf)
#     print(111111111,vars(bf))
#     print('django 自带form 使用\n ',bf['fileInput'].file.getvalue())
#     pic = SaveImage.objects.create(user=request.user,image_file=bf['fileInput'])
#     # return Response({'image_path': pic.image_file.url})
#     return redirect('im:talkRoom')

im/templates/im/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>CHATROOM</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">  
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<link rel='stylesheet' href="{% static 'im/css/chatroom.css' %}" type="text/css">
	<script src="{% static 'im/js/chatroom.js' %}"></script>

</head>
<body>
  <div style=" width:750px; margin:auto;">
	<h2 style="font-family:FangSong;font-weight:bold;color:rgb(228, 9, 9)">聊天屋</h2>

	<nav class="navbar navbar-default"  style='margin-bottom: 6px;'>
		<div class="container-fluid">
		  <div class="navbar-header">
			<a class="navbar-brand" href="#">Nothing</a>
		  </div>
		  <ul class="nav navbar-nav">
			{% if user.is_authenticated %}
				<li class="active" onclick="checkForm('sn')" id='bugo1'><a href="{% url 'im:getLogout'  %}"> Hello <span id='username'>{{ user.username }}</span>退出</a></li>
			{% else %}
				<li class="a" onclick="checkForm('sn')" id='bugo1'><a href="{% url 'im:signup' %}">注册</a></li>
				<li class="a" onclick="checkForm('sn')" id='bugo1'><a href="{% url 'login' %}">登录</a></li>
			{% endif %}
			
			
		  </ul>
		</div>
	</nav>

	{% block content %}
	<!--内容填充-->
	{% endblock %}

</body>
</html>

im/templates/im/chatroom2.html
{% extends "im/base.html" %}

{% block content %}

<div id="container">
    <aside id='user_list'> 
        <!-- 联系人名单 -->
        <header>
            <input type="text" placeholder="search">
        </header>
        <ul id="username_list">
        
        </ul>
    </aside>
    <main id="main">
        <header>
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_01.jpg" alt="">
            <div>
                <h2>{{ user.username }}</h2>
                <h3>just a test</h3>
            </div>
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/ico_star.png" alt="">
        </header>
        <ul id="chat">
            <a href="#"  id="history" class="history" onclick="gethistory()">history message</a>
        </ul>
        <footer>
            <textarea placeholder="Type your message" id='inpumessage' onkeyup="if(event.keyCode == 13){post_message()}"></textarea>
            <div id="emoji" style="display: none;">
                <span id='e1' onclick="check_emoji(this)" ><img src="/media/emoji/face-with-tears-of-joy_1f602(1).png"></span>
                <span id='e2' onclick="check_emoji(this)" ><img src="/media/emoji/face-with-tears-of-joy_1f602.png"></span>
                <span id='e3' onclick="check_emoji(this)" ><img src="/media/emoji/grinning-face_1f600.png"></span>
                <span id='e4' onclick="check_emoji(this)" ><img src="/media/emoji/smiling-face-with-open-mouth-and-cold-sweat_1f605.png"></span>
            </div>
            <input maxlength="80" name="sender" type="text" style="display: none;" placeholder="消息发送"> 
            <div>
                <span><button name="sender" id='messagebutton' onclick="post_message()">Message</button></span>
                <span><button name="sendere" id='emojibutton'  onclick="emoji()">Emoji</button></span>
                <span>
                    <button id ="select_file" onclick="related_image()">Select Image</button>
                    <input type="file" id="fileinput" name='file' style="display: none;" accept="image/*" />
                </span>
            </div>
                
        </footer>
    </main>
</div>


{% endblock %}

im/templates/im/signup.html
{% extends 'im/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}